#!/usr/bin/bash

if test -s secreto.txt
then
	x=$(cat secreto.txt)
else
	x=$(expr $RANDOM % 10)
fi

echo $x

echo Introduce un número entre 1 y 10
read y

if test $y gt 10 -o $y lt 1
then
	echo número fuera de rango
	exit 1
else
	echo Leido $y
fi

while test $x != $y
do
	if test $x -gt $y; then
		echo tu número es menor que el resultado, prueba otra vez
		read y
	else
		echo tu número es mayor que el resultado, prueba otra vez
		read y
	fi
done

echo Correcto!
