#!/usr/bin/bash

URL=https://storage.googleapis.com/aso-git-pei1/cards.txt
DEST_CLOUD_STORAGE=aso-git-pei1

for month in $(seq -f "%02g" 01 12)
do
    for year in $(seq 21 31)
    do
        filename=expire-$month-$year.txt
        # descargar con curl, filtrar aquellas líneas que contengan el
        # correspondiente $month/$year, eliminar el campo del nombre,
        # por ejemplo con `cut` y generar el archivo correspondiente,
        # por ejemplo usando una redirección de salida
        curl -s $URL | grep $month/$year | cut -d, -f1,3,4,5,6 >> $filename
    done
done

# Copiar todos los archivos que empiecen por `expire*` al bucket de destino
sudo gsutil cp expire* gs://silviu_1/
